name: Deploy CV to Hetzner VM

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          # Create deployment directory structure
          ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "sudo mkdir -p /var/www/html/css /var/www/html/images"
          
          # Copy HTML files
          scp *.html ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/tmp/
          ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "sudo mv /tmp/*.html /var/www/html/"
          
          # Copy CSS files
          scp css/*.css ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/tmp/
          ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "sudo mv /tmp/*.css /var/www/html/css/"
          
          # Copy images
          scp images/* ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/tmp/
          ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "sudo mv /tmp/me.jpg /var/www/html/images/ 2>/dev/null || true"
          
          # Set proper permissions
          ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "sudo chown -R www-data:www-data /var/www/html && sudo chmod -R 644 /var/www/html && sudo find /var/www/html -type d -exec chmod 755 {} \;"
          
          # Reload nginx
          ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "sudo systemctl reload nginx"

      - name: Cleanup SSH key
        if: always()
        run: |
          rm -f ~/.ssh/id_rsa